# Generated by Django 3.0.6 on 2020-05-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='key',
            field=models.CharField(default='3fd8555c2aacd923c362', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='started_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
