version: '3.7'

services:
  app:
    build: ./mystreaming
    container_name: mystreaming
    ports:
      - 4000:8000
    restart: always
    volumes:
      - ./mystreaming:/app

  rtmp_server:
    build: ./docker/nginx
    container_name: rtmp_enginx
    ports: 
      - 8000:8000
      - 443:443
      - 1935:1935
    restart: always

  ffmpeg_server:
    build: ./docker/ffmpeg
    container_name: ffmpeg_encoding
