version: '3.7'

services:
  web:
    build: ./mystreaming
    container_name: "mystreaming"
    ports:
      - 8000:8000
    restart: always
    volumes:
      - ./mystreaming:/app

  rtmp:
    build: ./docker/nginx
    container_name: "nginx_rtmp"
    ports: 
      - 8000:8000
      - 443:443
      - 1935:1935
    restart: always

  ffmpeg:
    build: ./docker/ffmpeg
    container_name: "ffmpeg_encoder"
